MtMoon_1F_Text_MarcosIntro::
    .string "WHOA!\n"
    .string "You startled me!\l"
    .string "...Oh, just a candidate.$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Wow!\n"
    .string "Startled again!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "New candidates should not\n"
    .string "wander here without focus.\p"
    .string "The cave repeats everything.$"

MtMoon_1F_Text_JoshIntro::
    .string "Did you come to study\n"
    .string "MOON NOISE CAVE too?$"

MtMoon_1F_Text_JoshDefeat::
    .string "Losing stinks!\n"
    .string "That was uncool.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "I came here to look brave.\n"
    .string "The cave did not agree.$"

MtMoon_1F_Text_MiriamIntro::
    .string "Wow! It is much bigger\n"
    .string "in here than I thought!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Oh!\n"
    .string "I lost focus!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "How do you get out?\n"
    .string "The echoes make every path\l"
    .string "feel the same.$"

MtMoon_1F_Text_JovanIntro::
    .string "What!\n"
    .string "Do not sneak up in a cave\l"
    .string "full of sound tricks!$"

MtMoon_1F_Text_JovanDefeat::
    .string "My BRAINROT will not do!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "I need stronger BRAINROTS.\n"
    .string "Maybe deeper in the cave?$"

MtMoon_1F_Text_IrisIntro::
    .string "What?\n"
    .string "I am waiting for my friends\l"
    .string "to find me here.$"

MtMoon_1F_Text_IrisDefeat::
    .string "I lost?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "I came because I heard\n"
    .string "there are rare fragments here.$"

MtMoon_1F_Text_KentIntro::
    .string "Masked people are in the cave.\n"
    .string "What about you?$"

MtMoon_1F_Text_KentDefeat::
    .string "You got me!$"

MtMoon_1F_Text_KentPostBattle::
    .string "I saw them!\n"
    .string "They kept whispering about\l"
    .string "the First Sound.$"

MtMoon_1F_Text_RobbyIntro::
    .string "You need to go through this cave\n"
    .string "to reach LICENSE C CITY.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "I lost.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "Cave BRAINROTS are tough!\n"
    .string "If you catch one, it can\l"
    .string "help against echoes.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Beware!\n"
    .string "Cave BRAINROTS react fast\l"
    .string "to sudden movement!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Hi, I am excavating old\n"
    .string "fragments here.\p"
    .string "Sometimes BROCK, the License D\n"
    .string "Examiner, helps me sort them.$"
