Route18_Text_WiltonIntro::
    .string "I check every grass patch\n"
    .string "for new BRAINROTS.$"

Route18_Text_WiltonDefeat::
    .string "Tch!$"

Route18_Text_WiltonPostBattle::
    .string "I wish I had a BIKE!$"

Route18_Text_RamiroIntro::
    .string "Kurukkoo!\n"
    .string "How is my birdcall?$"

Route18_Text_RamiroDefeat::
    .string "I had to bug you!$"

Route18_Text_RamiroPostBattle::
    .string "I collect sea BRAINROTS\n"
    .string "on weekends.$"

Route18_Text_JacobIntro::
    .string "This is my route!\n"
    .string "Let us battle!$"

Route18_Text_JacobDefeat::
    .string "Darn!$"

Route18_Text_JacobPostBattle::
    .string "This is my favorite area\n"
    .string "for catching BRAINROTS.$"

Route18_Text_RouteSign::
    .string "WILD RESERVE ROAD 18\n"
    .string "SKIBIDY CITY - WILD RESERVE CITY$"

Route18_Text_CyclingRoadSign::
    .string "SKIBIDY SLOPE ROAD\n"
    .string "No pedestrians permitted!$"
