Route19_Text_RichardIntro::
    .string "I warm up before swimming\n"
    .string "through sea signals.$"

Route19_Text_RichardDefeat::
    .string "All warmed up!$"

Route19_Text_RichardPostBattle::
    .string "Thanks, candidate!\n"
    .string "I am ready for the waves.$"

Route19_Text_ReeceIntro::
    .string "Wait! Slow down!\n"
    .string "The sea current is rough!$"

Route19_Text_ReeceDefeat::
    .string "Ooh!\n"
    .string "That is chilly!$"

Route19_Text_ReecePostBattle::
    .string "Watch out for sea BRAINROTS.\n"
    .string "Some sting badly.$"

Route19_Text_MatthewIntro::
    .string "I love swimming!\n"
    .string "What about you?$"

Route19_Text_MatthewDefeat::
    .string "Belly flop!$"

Route19_Text_MatthewPostBattle::
    .string "I can even race marine\n"
    .string "BRAINROTS.$"

Route19_Text_DouglasIntro::
    .string "What is beyond the horizon?$"

Route19_Text_DouglasDefeat::
    .string "Glub!$"

Route19_Text_DouglasPostBattle::
    .string "I see frozen islands\n"
    .string "far away!$"

Route19_Text_DavidIntro::
    .string "I tried diving for BRAINROTS,\n"
    .string "but no luck.$"

Route19_Text_DavidDefeat::
    .string "Help!$"

Route19_Text_DavidPostBattle::
    .string "Maybe fishing works better\n"
    .string "for sea BRAINROTS.$"

Route19_Text_TonyIntro::
    .string "I look at the sea to\n"
    .string "quiet my thoughts.$"

Route19_Text_TonyDefeat::
    .string "Ooh!\n"
    .string "Too intense!$"

Route19_Text_TonyPostBattle::
    .string "The sea makes memory feel\n"
    .string "far away.$"

Route19_Text_AnyaIntro::
    .string "Oh, I love your ride!\n"
    .string "Can I try it if I win?$"

Route19_Text_AnyaDefeat::
    .string "Oh! I lost!$"

Route19_Text_AnyaPostBattle::
    .string "It is still far to\n"
    .string "FROST ECHO ISLANDS...\p"
    .string "I want to go back.$"

Route19_Text_AliceIntro::
    .string "Swimming is great!\n"
    .string "Sunburns are not!$"

Route19_Text_AliceDefeat::
    .string "Shocker!$"

Route19_Text_AlicePostBattle::
    .string "My boyfriend wanted to swim\n"
    .string "to FROST ECHO ISLANDS.$"

Route19_Text_AxleIntro::
    .string "Ahoy!\n"
    .string "These waters are tricky!$"

Route19_Text_AxleDefeat::
    .string "Ooh!\n"
    .string "Dangerous!$"

Route19_Text_AxlePostBattle::
    .string "My legs cramped up!\n"
    .string "Glub, glub...$"

Route19_Text_ConnieIntro::
    .string "I swam here with friends...\n"
    .string "I am tired...$"

Route19_Text_ConnieDefeat::
    .string "I am exhausted...$"

Route19_Text_ConniePostBattle::
    .string "If I ride a sea BRAINROT,\n"
    .string "I want a big steady one.$"

Route19_Text_RouteSign::
    .string "SEA TEST ROAD 19\n"
    .string "WILD RESERVE CITY - FROST ECHO ISLANDS$"

Route19_Text_LiaIntro::
    .string "LIA: I am watching my brother.\n"
    .string "He just became a candidate.$"

Route19_Text_LiaDefeat::
    .string "LIA: That is no way to\n"
    .string "treat my little brother!$"

Route19_Text_LiaPostBattle::
    .string "LIA: Do you have a younger\n"
    .string "brother? Teach him well.$"

Route19_Text_LiaNotEnoughMons::
    .string "LIA: We battle together.\p"
    .string "Bring two BRAINROTS.$"

Route19_Text_LucIntro::
    .string "LUC: Sis taught me to swim\n"
    .string "and handle BRAINROTS.$"

Route19_Text_LucDefeat::
    .string "LUC: Wow!\n"
    .string "Stronger than my big sis!$"

Route19_Text_LucPostBattle::
    .string "LUC: My big sis is strong\n"
    .string "and nice.$"

Route19_Text_LucNotEnoughMons::
    .string "LUC: I only battle with sis.\p"
    .string "Bring two BRAINROTS.$"
