Route20_Text_BarryIntro::
    .string "The water is shallow here.\n"
    .string "Lots of candidates swim.$"

Route20_Text_BarryDefeat::
    .string "Splash!$"

Route20_Text_BarryPostBattle::
    .string "I wish I could ride\n"
    .string "a sea BRAINROT.$"

Route20_Text_ShirleyIntro::
    .string "FROST ECHO is quiet.\n"
    .string "I am resting here.$"

Route20_Text_ShirleyDefeat::
    .string "Quit it!$"

Route20_Text_ShirleyPostBattle::
    .string "There is a huge cavern\n"
    .string "under this island.$"

Route20_Text_TiffanyIntro::
    .string "I love floating with\n"
    .string "sea BRAINROTS here.$"

Route20_Text_TiffanyDefeat::
    .string "Yowch!$"

Route20_Text_TiffanyPostBattle::
    .string "Want to float too?$"

Route20_Text_IreneIntro::
    .string "Are you on break too?$"

Route20_Text_IreneDefeat::
    .string "No mercy at all!$"

Route20_Text_IrenePostBattle::
    .string "FROST ECHO used to feel\n"
    .string "like one island long ago.$"

Route20_Text_DeanIntro::
    .string "Check out my training!$"

Route20_Text_DeanDefeat::
    .string "Wimpy!$"

Route20_Text_DeanPostBattle::
    .string "I should train my BRAINROTS\n"
    .string "as much as myself.$"

Route20_Text_DarrinIntro::
    .string "Why ride a BRAINROT?\n"
    .string "Can you not swim?$"

Route20_Text_DarrinDefeat::
    .string "Ouch!\n"
    .string "Torpedoed!$"

Route20_Text_DarrinPostBattle::
    .string "Riding a BRAINROT\n"
    .string "looks fun!$"

Route20_Text_RogerIntro::
    .string "I rode my flying\n"
    .string "BRAINROT here.$"

Route20_Text_RogerDefeat::
    .string "Oh no!\n"
    .string "Now what do I do?$"

Route20_Text_RogerPostBattle::
    .string "My birds are exhausted.\n"
    .string "They cannot FLY back!$"

Route20_Text_NoraIntro::
    .string "My boyfriend gave me\n"
    .string "big pearls.$"

Route20_Text_NoraDefeat::
    .string "Oh no!\n"
    .string "My pearls were in them!$"

Route20_Text_NoraPostBattle::
    .string "Will pearls grow bigger\n"
    .string "inside shell BRAINROTS?$"

Route20_Text_MissyIntro::
    .string "I swam here from\n"
    .string "EXPERIMENT ISLAND.\p"
    .string "It was not easy.$"

Route20_Text_MissyDefeat::
    .string "I am so disappointed!$"

Route20_Text_MissyPostBattle::
    .string "BRAINROTS took over an\n"
    .string "abandoned mansion there.\p"
    .string "People call it the\n"
    .string "Experiment Mansion now.$"

Route20_Text_MelissaIntro::
    .string "EXPERIMENT ISLAND has\n"
    .string "a COGNIA LAB.\p"
    .string "My dad works there.$"

Route20_Text_MelissaDefeat::
    .string "Wait!\n"
    .string "You were supposed to wait!$"

Route20_Text_MelissaPostBattle::
    .string "EXPERIMENT ISLAND rose\n"
    .string "from volcanic stone.$"

Route20_Text_SeafoamIslands::
    .string "FROST ECHO ISLANDS$"

Route20_Text_MistyTrainsHere::
    .string "Strong candidates and\n"
    .string "water BRAINROTS train here.\p"
    .string "License C students visit often.$"
