Route21_South_Text_JackIntro::
	.string "I caught my BRAINROT\n"
	.string "at sea.$"

Route21_South_Text_JackDefeat::
	.string "Diver!\n"
	.string "Down!$"

Route21_South_Text_JackPostBattle::
	.string "Where did you catch\n"
	.string "your BRAINROTS?$"

Route21_South_Text_JeromeIntro::
	.string "Right now, I am doing\n"
	.string "a triathlon meet.$"

Route21_South_Text_JeromeDefeat::
	.string "Pant...\n"
	.string "Pant... Pant...$"

Route21_South_Text_JeromePostBattle::
	.string "I am beat! Still have bike\n"
	.string "and marathon left!$"

Route21_South_Text_RolandIntro::
	.string "Ahh!\n"
	.string "Feel the sun and wind!$"

Route21_South_Text_RolandDefeat::
	.string "Yow!\n"
	.string "I lost!$"

Route21_South_Text_RolandPostBattle::
	.string "I am sunburnt already!$"

Route21_South_Text_ClaudeIntro::
	.string "Hey, do not scare away\n"
	.string "the sea BRAINROTS!$"

Route21_South_Text_ClaudeDefeat::
	.string "Sorry! I am frustrated\n"
	.string "from catching nothing.$"

Route21_South_Text_ClaudePostBattle::
	.string "I have not caught a thing.\n"
	.string "Is this sea just a giant pool?$"

Route21_South_Text_NolanIntro::
	.string "Keep me company until\n"
	.string "I get a signal bite.$"

Route21_South_Text_NolanDefeat::
	.string "That passed some time.$"

Route21_South_Text_NolanPostBattle::
	.string "Oh wait!\n"
	.string "I got a bite! Yeah!$"

Route21_North_Text_LilIntro::
	.string "LIL: Huh? A battle?\n"
	.string "IAN, can you do it?$"

Route21_North_Text_LilDefeat::
	.string "LIL: See?\n"
	.string "We lost. Happy?$"

Route21_North_Text_LilPostBattle::
	.string "LIL: I am tired.\n"
	.string "Can we go home?$"

Route21_North_Text_LilNotEnoughMons::
	.string "LIL: I will not battle alone.\l"
	.string "Bring two BRAINROTS.$"

Route21_North_Text_IanIntro::
	.string "IAN: My sis needs exercise,\n"
	.string "so I made her come.$"

Route21_North_Text_IanDefeat::
	.string "IAN: Awww, Sis!\n"
	.string "Focus!$"

Route21_North_Text_IanPostBattle::
	.string "IAN: Come on, Sis!\p"
	.string "You need more training!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: We want two-on-two.\n"
	.string "Bring two BRAINROTS.$"
