PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} checked the old game.\p"
    .string "For a second, the screen\n"
    .string "showed a familiar name.\p"
    .string "LUNA.$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It is a posted notice...\p"
    .string "If your thoughts feel noisy,\n"
    .string "ask for HELP.\p"
    .string "Press the L or R Button!$"
