Route17_Text_RaulIntro::
    .string "No quick riches in\n"
    .string "candidate battles.$"

Route17_Text_RaulDefeat::
    .string "Burned out!$"

Route17_Text_RaulPostBattle::
    .string "You can find good stuff\n"
    .string "on this slope.\p"
    .string "People drop items all the time.$"

Route17_Text_IsaiahIntro::
    .string "I am proud of my training,\n"
    .string "candidate. Come on!$"

Route17_Text_IsaiahDefeat::
    .string "Whoo!$"

Route17_Text_IsaiahPostBattle::
    .string "This road gives a real workout!$"

Route17_Text_VirgilIntro::
    .string "Heading to WILD RESERVE CITY?$"

Route17_Text_VirgilDefeat::
    .string "Crash and burn!$"

Route17_Text_VirgilPostBattle::
    .string "I love racing downhill!$"

Route17_Text_BillyIntro::
    .string "We are ROAD RIDERS!\n"
    .string "We rule the slope, man!$"

Route17_Text_BillyDefeat::
    .string "Smoked!$"

Route17_Text_BillyPostBattle::
    .string "Looking for road adventure?$"

Route17_Text_NikolasIntro::
    .string "Let my electric BRAINROT\n"
    .string "wake you up!$"

Route17_Text_NikolasDefeat::
    .string "Grounded out!$"

Route17_Text_NikolasPostBattle::
    .string "I caught mine near the\n"
    .string "OLD POWER PLANT.$"

Route17_Text_ZeekIntro::
    .string "I leveled my BRAINROT,\n"
    .string "but it will not evolve. Why?$"

Route17_Text_ZeekDefeat::
    .string "Why, you!$"

Route17_Text_ZeekPostBattle::
    .string "Some BRAINROTS need\n"
    .string "element stones to evolve.$"

Route17_Text_JamalIntro::
    .string "I need a little exercise!$"

Route17_Text_JamalDefeat::
    .string "Whew!\n"
    .string "Good workout!$"

Route17_Text_JamalPostBattle::
    .string "I lost weight there for sure!$"

Route17_Text_CoreyIntro::
    .string "Be bold!$"

Route17_Text_CoreyDefeat::
    .string "Aaaargh!$"

Route17_Text_CoreyPostBattle::
    .string "Stand up for what you believe!$"

Route17_Text_JaxonIntro::
    .string "Nice BIKE!\n"
    .string "How does it handle?$"

Route17_Text_JaxonDefeat::
    .string "Shoot!$"

Route17_Text_JaxonPostBattle::
    .string "The slope makes steering hard.$"

Route17_Text_WilliamIntro::
    .string "Move along, candidate!\n"
    .string "I am tired!$"

Route17_Text_WilliamDefeat::
    .string "Satisfied now?$"

Route17_Text_WilliamPostBattle::
    .string "I need a quick nap.$"

Route17_Text_WatchOutForDiscardedItems::
    .string "It is a notice.\p"
    .string "Watch out for discarded items.$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "TRAINER TIPS\p"
    .string "All BRAINROTS are unique.\p"
    .string "Even same species and level\n"
    .string "can grow differently.$"

Route17_Text_PressBToStayInPlace::
    .string "TRAINER TIPS\p"
    .string "Press B to stay in place\n"
    .string "while on a slope.$"

Route17_Text_RouteSign::
    .string "SKIBIDY SLOPE ROAD 17\n"
    .string "SKIBIDY CITY - WILD RESERVE CITY$"

Route17_Text_DontThrowGameThrowBalls::
    .string "It is a notice!\p"
    .string "Do not throw the game.\n"
    .string "Throw BRAINROT BALLS instead!$"

Route17_Text_CyclingRoadSign::
    .string "SKIBIDY SLOPE ROAD\n"
    .string "Slope ends here!$"
