Route4_Text_TrippedOverGeodude::
    .string "Ouch! I tripped over a rocky\n"
    .string "BRAINROT!$"

Route4_Text_CrissyIntro::
    .string "I came to MOON NOISE CAVE\n"
    .string "looking for mushroom BRAINROTS.$"

Route4_Text_CrissyDefeat::
    .string "After all I did to catch them!$"

Route4_Text_CrissyPostBattle::
    .string "There may be no more\n"
    .string "mushroom signals here.\p"
    .string "I think I tracked them all.$"

Route4_Text_MtMoonEntrance::
    .string "MOON NOISE CAVE\n"
    .string "Main Entrance$"

Route4_Text_RouteSign::
    .string "TEST ROAD 04\n"
    .string "MOON NOISE CAVE - LICENSE C CITY$"

Text_MegaPunchTeach::
    .string "A punch with heavy focus!\p"
    .string "Packed with direct power!\p"
    .string "MEGA PUNCH is simple,\n"
    .string "but it hits like a test stamp.\p"
    .string "Let me teach it to\n"
    .string "one of your BRAINROTS!$"

Text_MegaPunchDeclined::
    .string "You will be back when you\n"
    .string "respect MEGA PUNCH.$"

Text_MegaPunchWhichMon::
    .string "Fine!\n"
    .string "Which BRAINROT will learn it?$"

Text_MegaPunchTaught::
    .string "Now we share the way of\n"
    .string "focused punching!$"

Text_MegaKickTeach::
    .string "A kick with brutal focus!\p"
    .string "Packed with raw force!\p"
    .string "MEGA KICK can turn a battle\n"
    .string "with one clean hit.\p"
    .string "Let me teach it to\n"
    .string "one of your BRAINROTS!$"

Text_MegaKickDeclined::
    .string "You will return when you\n"
    .string "value MEGA KICK.$"

Text_MegaKickWhichMon::
    .string "All right!\n"
    .string "Which BRAINROT wants it?$"

Text_MegaKickTaught::
    .string "Now we share the way of\n"
    .string "focused kicking!$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Oh wow, that is the STONEBADGE!\n"
    .string "You passed BROCK's test?\p"
    .string "BROCK is strict, but fair.\n"
    .string "People respect him.\p"
    .string "I want to become an examiner\n"
    .string "like him.$"
