Route21_North_Text_RonaldIntro::
	.string "Want to know if the\n"
	.string "sea signals are biting?$"

Route21_North_Text_RonaldDefeat::
	.string "Dang!$"

Route21_North_Text_RonaldPostBattle::
	.string "I cannot catch anything good.\n"
	.string "Not one rare BRAINROT today!$"

Route21_North_Text_WadeIntro::
	.string "I got a big haul!\n"
	.string "Want to test it?$"

Route21_North_Text_WadeDefeat::
	.string "Heheh, weak fish Brainrots\n"
	.string "still need training.$"

Route21_North_Text_WadePostBattle::
	.string "I keep catching the same\n"
	.string "weak sea BRAINROTS!$"

Route21_North_Text_SpencerIntro::
	.string "The sea clears my body\n"
	.string "and mind!$"

Route21_North_Text_SpencerDefeat::
	.string "Ayah!$"

Route21_North_Text_SpencerPostBattle::
	.string "The sea is great, but\n"
	.string "the mountains echo too.$"

Route21_North_Text_CueBallIntro::
	.string "I swim here sometimes too!$"

Route21_North_Text_CueBallDefeat::
	.string "Gwaa!$"

Route21_North_Text_CueBallPostBattle::
	.string "What do I look like?\n"
	.string "A floating tire?$"
