Route15_Text_KindraIntro::
    .string "I got some traded BRAINROTS.\n"
    .string "Can I test them on you?$"

Route15_Text_KindraDefeat::
    .string "Not good enough!$"

Route15_Text_KindraPostBattle::
    .string "Only the original handler\n"
    .string "can change a nickname.$"

Route15_Text_BeckyIntro::
    .string "You look gentle, so maybe\n"
    .string "I can beat you.$"

Route15_Text_BeckyDefeat::
    .string "No, wrong!$"

Route15_Text_BeckyPostBattle::
    .string "Some bikers look scary,\n"
    .string "but most just like roads.$"

Route15_Text_EdwinIntro::
    .string "When I whistle, flying\n"
    .string "BRAINROTS answer.$"

Route15_Text_EdwinDefeat::
    .string "Ow!\n"
    .string "That is tragic!$"

Route15_Text_EdwinPostBattle::
    .string "Maybe battles are not\n"
    .string "my right type.$"

Route15_Text_ChesterIntro::
    .string "Hmm? My birds are shivering!\n"
    .string "You are good, right?$"

Route15_Text_ChesterDefeat::
    .string "Just as I thought!$"

Route15_Text_ChesterPostBattle::
    .string "Ground moves miss flying\n"
    .string "BRAINROTS. Simple but important.$"

Route15_Text_GraceIntro::
    .string "Oh, you are a little cutie!\n"
    .string "Like a darling BRAINROT!$"

Route15_Text_GraceDefeat::
    .string "You looked so cute, too!$"

Route15_Text_GracePostBattle::
    .string "I forgive you.\n"
    .string "I can take it.$"

Route15_Text_OliviaIntro::
    .string "I raise BRAINROTS for\n"
    .string "protection because I live alone.$"

Route15_Text_OliviaDefeat::
    .string "For me, BRAINROTS are not\n"
    .string "just about winning.$"

Route15_Text_OliviaPostBattle::
    .string "Having a partner greet me\n"
    .string "at home feels safe.$"

Route15_Text_ErnestIntro::
    .string "Hey, candidate! C'mon!\n"
    .string "I got these in a trade.$"

Route15_Text_ErnestDefeat::
    .string "Why not?$"

Route15_Text_ErnestPostBattle::
    .string "Life is short.\n"
    .string "The road is louder than rules.$"

Route15_Text_AlexIntro::
    .string "If you lose, you owe me\n"
    .string "respect, candidate!$"

Route15_Text_AlexDefeat::
    .string "That cannot be true!$"

Route15_Text_AlexPostBattle::
    .string "I was joking.\n"
    .string "Do not take me serious.$"

Route15_Text_CeliaIntro::
    .string "What is cool lately?\n"
    .string "Trading BRAINROTS!$"

Route15_Text_CeliaDefeat::
    .string "I said trade!$"

Route15_Text_CeliaPostBattle::
    .string "I trade BRAINROTS with\n"
    .string "friends all the time.$"

Route15_Text_YazminIntro::
    .string "Want to play with my\n"
    .string "BRAINROTS?$"

Route15_Text_YazminDefeat::
    .string "I was too impatient!$"

Route15_Text_YazminPostBattle::
    .string "I will train with easier\n"
    .string "candidates first.$"

Route15_Text_RouteSign::
    .string "WILD RESERVE ROAD 15\n"
    .string "West to WILD RESERVE CITY$"

Route15_Text_MyaIntro::
    .string "MYA: Perfect.\n"
    .string "Help me train my brother?$"

Route15_Text_MyaDefeat::
    .string "MYA: RON, focus!\n"
    .string "Watch your BRAINROT!$"

Route15_Text_MyaPostBattle::
    .string "MYA: Fine, we turn it up.\n"
    .string "New training menu!$"

Route15_Text_MyaNotEnoughMons::
    .string "MYA: Challenge us with\n"
    .string "two BRAINROTS.$"

Route15_Text_RonIntro::
    .string "RON: My sister gets intense\n"
    .string "when we lose.$"

Route15_Text_RonDefeat::
    .string "RON: Oh no...\n"
    .string "Sis, sorry!$"

Route15_Text_RonPostBattle::
    .string "RON: I wish training\n"
    .string "was softer...$"

Route15_Text_RonNotEnoughMons::
    .string "RON: Want a double battle?\p"
    .string "You need two BRAINROTS.$"
