Route16_Text_LaoIntro::
    .string "What do you want?$"

Route16_Text_LaoDefeat::
    .string "Do not laugh!$"

Route16_Text_LaoPostBattle::
    .string "We just hang around here.\n"
    .string "Road noise helps us think.$"

Route16_Text_KojiIntro::
    .string "Nice BIKE!\n"
    .string "How fast does it handle?$"

Route16_Text_KojiDefeat::
    .string "Knockout!$"

Route16_Text_KojiPostBattle::
    .string "Forget it, keep your BIKE!$"

Route16_Text_LukeIntro::
    .string "Come out and battle,\n"
    .string "little candidate!$"

Route16_Text_LukeDefeat::
    .string "You little rat!$"

Route16_Text_LukePostBattle::
    .string "I hate losing!\n"
    .string "Move along!$"

Route16_Text_HideoIntro::
    .string "Hey, you bumped my bike!$"

Route16_Text_HideoDefeat::
    .string "Kaboom!$"

Route16_Text_HideoPostBattle::
    .string "You can detour to SOUND PORT\n"
    .string "from WILD RESERVE CITY\l"
    .string "along the coast.$"

Route16_Text_CamronIntro::
    .string "I am hungry and cranky!\n"
    .string "Battle me!$"

Route16_Text_CamronDefeat::
    .string "Bad, bad, bad!$"

Route16_Text_CamronPostBattle::
    .string "If I raise BRAINROTS,\n"
    .string "I want fierce ones.$"

Route16_Text_RubenIntro::
    .string "Hey there!\n"
    .string "Let us have a good time!$"

Route16_Text_RubenDefeat::
    .string "Do not make me annoyed!$"

Route16_Text_RubenPostBattle::
    .string "Some BRAINROTS are great\n"
    .string "for startling people.$"

Route16_Text_MonSprawledOutInSlumber::
    .string "A huge BRAINROT is sprawled\n"
    .string "out in deep slumber.$"

Route16_Text_CyclingRoadSign::
    .string "Enjoy the slope!\n"
    .string "SKIBIDY GATE ROAD$"

Route16_Text_RouteSign::
    .string "SKIBIDY GATE ROAD 16\n"
    .string "SKIBIDY CITY - WILD RESERVE CITY$"

Route16_Text_JedIntro::
    .string "JED: Our focus knows no bounds.\n"
    .string "We battle together!$"

Route16_Text_JedDefeat::
    .string "JED: Oh no!\n"
    .string "LEA saw me lose!$"

Route16_Text_JedPostBattle::
    .string "JED: LEA, we need\n"
    .string "more battle focus.$"

Route16_Text_JedNotEnoughMons::
    .string "JED: Just one BRAINROT?\p"
    .string "Bring two for a double battle.$"

Route16_Text_LeaIntro::
    .string "LEA: Sometimes our teamwork\n"
    .string "scares me.$"

Route16_Text_LeaDefeat::
    .string "LEA: Ohh! But JED\n"
    .string "still looked cool.$"

Route16_Text_LeaPostBattle::
    .string "LEA: Ehehe, sorry.\n"
    .string "JED is so focused.$"

Route16_Text_LeaNotEnoughMons::
    .string "LEA: You need two BRAINROTS\n"
    .string "for our double battle.$"
