Route6_Text_RickyIntro::
    .string "Who is there?\n"
    .string "Quit listening to our route plan!$"

Route6_Text_RickyDefeat::
    .string "I just cannot win!$"

Route6_Text_RickyPostBattle::
    .string "Whisper...\n"
    .string "SOUND PORT is strict...$"

Route6_Text_NancyIntro::
    .string "Excuse me!\n"
    .string "This is private candidate talk!$"

Route6_Text_NancyDefeat::
    .string "Ugh!\n"
    .string "I hate losing.$"

Route6_Text_NancyPostBattle::
    .string "Whisper...\n"
    .string "The underground path feels watched.$"

Route6_Text_KeigoIntro::
    .string "There are not many forest\n"
    .string "BRAINROTS out here.$"

Route6_Text_KeigoDefeat::
    .string "No!\n"
    .string "You are kidding!$"

Route6_Text_KeigoPostBattle::
    .string "I like forest types, so I may\n"
    .string "return to ZONE GREEN 01.$"

Route6_Text_JeffIntro::
    .string "Huh?\n"
    .string "You want to test me?$"

Route6_Text_JeffDefeat::
    .string "This stinks...\n"
    .string "I failed the challenge.$"

Route6_Text_JeffPostBattle::
    .string "I should bring more BRAINROTS.\n"
    .string "I feel safer that way.$"

Route6_Text_IsabelleIntro::
    .string "Me?\n"
    .string "Okay, I will test battle!$"

Route6_Text_IsabelleDefeat::
    .string "Things just did not work...$"

Route6_Text_IsabellePostBattle::
    .string "I want to get stronger.\n"
    .string "What keeps your focus steady?$"

Route6_Text_ElijahIntro::
    .string "I have never seen you around.\n"
    .string "Are you good?$"

Route6_Text_ElijahDefeat::
    .string "You are too good!$"

Route6_Text_ElijahPostBattle::
    .string "Are my BRAINROTS weak?\n"
    .string "Or am I just bad?\l"
    .string "Which do you think?$"

Route6_Text_UndergroundPathSign::
    .string "UNDERGROUND SAFE PATH\n"
    .string "LICENSE C CITY - SOUND PORT$"
