Route3_Text_TunnelFromCeruleanTiring::
    .string "Whew... I need a rest...\n"
    .string "That tunnel ahead has echoes\l"
    .string "that make your head buzz.$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "I saw you in ZONE GREEN 01!$"

Route3_Text_ColtonDefeat::
    .string "You beat me again!$"

Route3_Text_ColtonPostBattle::
    .string "Forest BRAINROTS are only\n"
    .string "the start.\p"
    .string "Cave ones react to echoes.$"

Route3_Text_BenIntro::
    .string "Hi!\n"
    .string "I like shorts!\p"
    .string "They are comfy and easy\n"
    .string "to run from noisy caves in!$"

Route3_Text_BenDefeat::
    .string "I do not believe it!$"

Route3_Text_BenPostBattle::
    .string "Do you use healing centers\n"
    .string "to store your BRAINROTS?\p"
    .string "Each BOX can hold up to\n"
    .string "30 BRAINROTS.$"

Route3_Text_JaniceIntro::
    .string "Excuse me!\n"
    .string "You looked focused, did you not?$"

Route3_Text_JaniceDefeat::
    .string "You are strong!$"

Route3_Text_JanicePostBattle::
    .string "Around here, eye contact\n"
    .string "usually means a test battle.$"

Route3_Text_GregIntro::
    .string "Are you a candidate?\n"
    .string "Let us test right away!$"

Route3_Text_GregDefeat::
    .string "If I had new BRAINROTS,\n"
    .string "I would have won!$"

Route3_Text_GregPostBattle::
    .string "If a BRAINROT BOX gets full,\n"
    .string "switch to another BOX.$"

Route3_Text_SallyIntro::
    .string "That look you gave me...\n"
    .string "It feels like field focus!$"

Route3_Text_SallyDefeat::
    .string "Be nice!$"

Route3_Text_SallyPostBattle::
    .string "You can avoid battles by\n"
    .string "staying out of sight lines.$"

Route3_Text_CalvinIntro::
    .string "Hey! You are not wearing\n"
    .string "field shorts!\p"
    .string "How do you run from echoes?$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "I always wear shorts, even\n"
    .string "near Moon Noise Cave.$"

Route3_Text_JamesIntro::
    .string "I will battle you with the\n"
    .string "BRAINROT I just caught.$"

Route3_Text_JamesDefeat::
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle::
    .string "Trained BRAINROTS are steadier\n"
    .string "than wild ones.$"

Route3_Text_RobinIntro::
    .string "Eek!\n"
    .string "Did the cave echo move?$"

Route3_Text_RobinDefeat::
    .string "That is it?$"

Route3_Text_RobinPostBattle::
    .string "TEST ROAD 04 is at the foot\n"
    .string "of MOON NOISE CAVE.$"

Route3_Text_RouteSign::
    .string "TEST ROAD 03\n"
    .string "MOON NOISE CAVE AHEAD$"
