MtMoon_B2F_Text_MiguelIntro::
    .string "Hey, stop!\p"
    .string "I found these fragments!\n"
    .string "They are both mine!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Okay!\n"
    .string "We can share!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "We will each take one fragment!\n"
    .string "No being greedy!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "All right.\n"
    .string "Then this one is mine!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Far away, on EXPERIMENT ISLAND,\n"
    .string "there is a COGNIA LAB.\p"
    .string "They study ancient fragments\n"
    .string "and old BRAINROT signals.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "We of the ECHO MASKS will\n"
    .string "collect these fragments!\p"
    .string "Old signals are worth\n"
    .string "more than money.$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Urgh!\n"
    .string "Now I am annoyed!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "You interrupted our work.\n"
    .string "The First Sound remembers that.$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "We are the ECHO MASKS.\l"
    .string "We follow the first rhythm.$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "I messed up!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "The others will not like this.\n"
    .string "The cave carries every word.$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "We are doing important work here!\n"
    .string "Leave, candidate!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "So, you are good...$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "If you find a fragment,\n"
    .string "hand it over and move on.$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "New candidates should not\n"
    .string "touch old cave signals.\p"
    .string "They echo back.$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "I am done!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "These BRAINROTS were here\n"
    .string "before people named them.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Do you want the DOME FRAGMENT?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Do you want the HELIX FRAGMENT?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Obtained the HELIX FRAGMENT!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Obtained the DOME FRAGMENT!$"
