Route25_Text_JoeyIntro::
    .string "Local candidates come here\n"
    .string "to practice.$"

Route25_Text_JoeyDefeat::
    .string "You are decent.$"

Route25_Text_JoeyPostBattle::
    .string "All BRAINROTS have weaknesses.\p"
    .string "That is why different types\n"
    .string "matter.$"

Route25_Text_DanIntro::
    .string "Dad took me to a big ship\n"
    .string "at SOUND PORT.$"

Route25_Text_DanDefeat::
    .string "I am not mad!$"

Route25_Text_DanPostBattle::
    .string "On the ship, I saw candidates\n"
    .string "from around the world.$"

Route25_Text_FlintIntro::
    .string "I am cool.\n"
    .string "I have a girlfriend!$"

Route25_Text_FlintDefeat::
    .string "Aww, darn...$"

Route25_Text_FlintPostBattle::
    .string "Oh well.\n"
    .string "My girlfriend will cheer me up.$"

Route25_Text_KelseyIntro::
    .string "Hi!\n"
    .string "My boyfriend is cool!$"

Route25_Text_KelseyDefeat::
    .string "My conditioning is not best...$"

Route25_Text_KelseyPostBattle::
    .string "I wish my boyfriend battled\n"
    .string "as well as you.$"

Route25_Text_ChadIntro::
    .string "I had this feeling...\n"
    .string "I knew we had to battle!$"

Route25_Text_ChadDefeat::
    .string "I knew I would lose too!$"

Route25_Text_ChadPostBattle::
    .string "If your BRAINROT gets confused,\n"
    .string "switching can help.$"

Route25_Text_HaleyIntro::
    .string "My friend has many cute\n"
    .string "BRAINROTS. I am jealous!$"

Route25_Text_HaleyDefeat::
    .string "I am not so jealous now!$"

Route25_Text_HaleyPostBattle::
    .string "You came from MOON NOISE CAVE?\n"
    .string "Did you see rare ones?$"

Route25_Text_FranklinIntro::
    .string "I just came from\n"
    .string "MOON NOISE CAVE,\n"
    .string "but I still have energy!$"

Route25_Text_FranklinDefeat::
    .string "You worked hard!$"

Route25_Text_FranklinPostBattle::
    .string "A cave BRAINROT startled me\n"
    .string "back there.$"

Route25_Text_NobIntro::
    .string "I am going to see a collector's\n"
    .string "BRAINROT data at the cape.$"

Route25_Text_NobDefeat::
    .string "You got me, real good!$"

Route25_Text_NobPostBattle::
    .string "That collector has rare\n"
    .string "BRAINROT records.$"

Route25_Text_WayneIntro::
    .string "You are going to see BILL?\n"
    .string "First, we battle!$"

Route25_Text_WayneDefeat::
    .string "You are something.$"

Route25_Text_WaynePostBattle::
    .string "The trail below is a shortcut\n"
    .string "to LICENSE C CITY.$"

Route25_Text_SeaCottageSign::
    .string "SEA COTTAGE\n"
    .string "BILL records BRAINROT data here!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "This cape is a famous quiet spot.\p"
    .string "License C students come here\n"
    .string "to clear their heads.$"

Route25_Text_AreYouHereAlone::
    .string "Hello, are you here alone?\p"
    .string "The cape is calmer with\n"
    .string "someone you trust.$"
