Route9_Text_AliciaIntro::
    .string "You have BRAINROTS with you!\n"
    .string "Then let us test battle!$"

Route9_Text_AliciaDefeat::
    .string "You beat my timing...$"

Route9_Text_AliciaPostBattle::
    .string "The tunnel ahead is dark\n"
    .string "and full of echoes.\p"
    .string "You will need FLASH.$"

Route9_Text_ChrisIntro::
    .string "Who is walking there with\n"
    .string "those sharp-looking BRAINROTS?$"

Route9_Text_ChrisDefeat::
    .string "Lights out for my plan!$"

Route9_Text_ChrisPostBattle::
    .string "Keep walking.\n"
    .string "ECHO TUNNEL is waiting.$"

Route9_Text_DrewIntro::
    .string "I am taking ECHO TUNNEL\n"
    .string "to reach MEMORY TOWN...$"

Route9_Text_DrewDefeat::
    .string "Cannot measure up...$"

Route9_Text_DrewPostBattle::
    .string "Are you heading to\n"
    .string "ECHO TUNNEL too?$"

Route9_Text_CaitlinIntro::
    .string "Do not underestimate me!$"

Route9_Text_CaitlinDefeat::
    .string "No!\n"
    .string "You are too much.$"

Route9_Text_CaitlinPostBattle::
    .string "You are obviously focused.\n"
    .string "Good luck in the tunnel.$"

Route9_Text_JeremyIntro::
    .string "Bwahaha!\n"
    .string "Great! I was bored!$"

Route9_Text_JeremyDefeat::
    .string "Keep it coming!\p"
    .string "Oh wait.\n"
    .string "I am out of BRAINROTS!$"

Route9_Text_JeremyPostBattle::
    .string "You had guts standing up\n"
    .string "to me there.$"

Route9_Text_BriceIntro::
    .string "Hahaha!\n"
    .string "Aren't you a tough candidate!$"

Route9_Text_BriceDefeat::
    .string "What was that?$"

Route9_Text_BricePostBattle::
    .string "Hahaha!\n"
    .string "Candidates should be tough!$"

Route9_Text_BrentIntro::
    .string "I got up early every day\n"
    .string "to raise cocoon Brainrots!$"

Route9_Text_BrentDefeat::
    .string "WHAT?\p"
    .string "What a waste of time!$"

Route9_Text_BrentPostBattle::
    .string "I need more than bug types\n"
    .string "to get stronger...$"

Route9_Text_AlanIntro::
    .string "Hahahaha!\n"
    .string "Bring it on!$"

Route9_Text_AlanDefeat::
    .string "Hahahaha!\n"
    .string "You beat me fair!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha!\n"
    .string "Steady people laugh loud!$"

Route9_Text_ConnerIntro::
    .string "Go, my super bug BRAINROTS!$"

Route9_Text_ConnerDefeat::
    .string "My bugs...$"

Route9_Text_ConnerPostBattle::
    .string "If you do not like bug types,\n"
    .string "you bug me!$"

Route9_Text_RouteSign::
    .string "TEST ROAD 09\n"
    .string "LICENSE C CITY - ECHO TUNNEL$"
