Route11_Text_HugoIntro::
    .string "Win, lose, or draw!\n"
    .string "Sound Port rules!$"

Route11_Text_HugoDefeat::
    .string "Atcha!\n"
    .string "Did not go my way!$"

Route11_Text_HugoPostBattle::
    .string "BRAINROTS are life!\n"
    .string "And life is one weird game!$"

Route11_Text_JasperIntro::
    .string "Competition!\n"
    .string "I cannot get enough!$"

Route11_Text_JasperDefeat::
    .string "I had a chance!$"

Route11_Text_JasperPostBattle::
    .string "You cannot lose focus\n"
    .string "in a BRAINROT battle!$"

Route11_Text_EddieIntro::
    .string "Let us go, but no cheap tricks!$"

Route11_Text_EddieDefeat::
    .string "Huh?\n"
    .string "That did not sync!$"

Route11_Text_EddiePostBattle::
    .string "I did my best.\n"
    .string "No regrets.$"

Route11_Text_BraxtonIntro::
    .string "Careful!\n"
    .string "I am laying down signal cables!$"

Route11_Text_BraxtonDefeat::
    .string "That was electric!$"

Route11_Text_BraxtonPostBattle::
    .string "Save energy.\n"
    .string "Old signals attract weird things.$"

Route11_Text_DillonIntro::
    .string "I just became a candidate.\n"
    .string "But I think I can win.$"

Route11_Text_DillonDefeat::
    .string "My BRAINROTS could not win...\n"
    .string "Are they still too young?$"

Route11_Text_DillonPostBattle::
    .string "What now?\n"
    .string "Let me train in peace!$"

Route11_Text_DirkIntro::
    .string "Fwahaha!\n"
    .string "I have never lost!$"

Route11_Text_DirkDefeat::
    .string "My first loss!$"

Route11_Text_DirkPostBattle::
    .string "You were just focused, that is all.$"

Route11_Text_DarianIntro::
    .string "I have never won before...$"

Route11_Text_DarianDefeat::
    .string "I saw this coming...$"

Route11_Text_DarianPostBattle::
    .string "I was unlucky, as always.$"

Route11_Text_YasuIntro::
    .string "I am the best in my class.\n"
    .string "I train every morning.$"

Route11_Text_YasuDefeat::
    .string "Darn!\n"
    .string "My BRAINROTS need power!$"

Route11_Text_YasuPostBattle::
    .string "A huge sleepy BRAINROT\n"
    .string "comes down from the mountains.\p"
    .string "I bet it is strong.$"

Route11_Text_BernieIntro::
    .string "Watch out for live wires!$"

Route11_Text_BernieDefeat::
    .string "Whoa!\n"
    .string "You spark plug!$"

Route11_Text_BerniePostBattle::
    .string "Better get back to work.$"

Route11_Text_DaveIntro::
    .string "I raised my BRAINROTS carefully.\n"
    .string "They should be ready now!$"

Route11_Text_DaveDefeat::
    .string "Bye-bye!\n"
    .string "Thank you, and good-bye!$"

Route11_Text_DavePostBattle::
    .string "Tch...\n"
    .string "I need stronger partners!$"

Route11_Text_DiglettsCave::
    .string "ECHO TUNNEL SIDE CAVE$"
