Route14_Text_CarterIntro::
    .string "Use TMs to teach strong\n"
    .string "moves to BRAINROTS.$"

Route14_Text_CarterDefeat::
    .string "Not good enough yet.$"

Route14_Text_CarterPostBattle::
    .string "HMs are hard to forget.\n"
    .string "Choose carefully.$"

Route14_Text_MitchIntro::
    .string "My flying BRAINROTS should\n"
    .string "be ready for battle.$"

Route14_Text_MitchDefeat::
    .string "Not ready yet!$"

Route14_Text_MitchPostBattle::
    .string "My flying BRAINROTS need\n"
    .string "better moves.$"

Route14_Text_BeckIntro::
    .string "TMs are sold in SKIBIDY CITY.\p"
    .string "TMs are common, but HMs\n"
    .string "are still special.$"

Route14_Text_BeckDefeat::
    .string "Aww, bummer!$"

Route14_Text_BeckPostBattle::
    .string "A move matching a BRAINROT's\n"
    .string "type can hit harder.$"

Route14_Text_MarlonIntro::
    .string "Have you taught a flying\n"
    .string "BRAINROT how to FLY?$"

Route14_Text_MarlonDefeat::
    .string "Shot down!$"

Route14_Text_MarlonPostBattle::
    .string "Flying BRAINROTS are my\n"
    .string "one true love.$"

Route14_Text_DonaldIntro::
    .string "Have you heard the legend\n"
    .string "of the winged mirages?$"

Route14_Text_DonaldDefeat::
    .string "Why?\n"
    .string "Why did I lose?$"

Route14_Text_DonaldPostBattle::
    .string "Three old winged signals\n"
    .string "exist in Kanto.\p"
    .string "COGNIA keeps their files sealed.$"

Route14_Text_BennyIntro::
    .string "I am not into it, but okay.\n"
    .string "Let us go!$"

Route14_Text_BennyDefeat::
    .string "I knew it!$"

Route14_Text_BennyPostBattle::
    .string "Winning and losing feel tiny\n"
    .string "under this huge sky.$"

Route14_Text_LukasIntro::
    .string "C'mon, c'mon.\n"
    .string "Let us go, go, go!$"

Route14_Text_LukasDefeat::
    .string "Arrg!\n"
    .string "Lost! Move on!$"

Route14_Text_LukasPostBattle::
    .string "What, what, what?\n"
    .string "What do you still want?$"

Route14_Text_IsaacIntro::
    .string "I need to burn some time.\n"
    .string "Battle me.$"

Route14_Text_IsaacDefeat::
    .string "What?\n"
    .string "You!?$"

Route14_Text_IsaacPostBattle::
    .string "Raising BRAINROTS can be\n"
    .string "a drag, man.$"

Route14_Text_GeraldIntro::
    .string "We ride here because of\n"
    .string "the wide-open road.$"

Route14_Text_GeraldDefeat::
    .string "Wipeout!$"

Route14_Text_GeraldPostBattle::
    .string "You trained your BRAINROTS\n"
    .string "well. That is real strength.$"

Route14_Text_MalikIntro::
    .string "BRAINROT battle?\n"
    .string "Cool! Rumble!$"

Route14_Text_MalikDefeat::
    .string "Blown away!$"

Route14_Text_MalikPostBattle::
    .string "You are strong, no joke.$"

Route14_Text_RouteSign::
    .string "WILD RESERVE ROAD 14\n"
    .string "West to WILD RESERVE CITY$"

Route14_Text_KiriIntro::
    .string "KIRI: JAN, let us try\n"
    .string "really hard together.$"

Route14_Text_KiriDefeat::
    .string "KIRI: Whimper...\n"
    .string "We lost, didn't we?$"

Route14_Text_KiriPostBattle::
    .string "KIRI: Did we lose because\n"
    .string "of me?$"

Route14_Text_KiriNotEnoughMons::
    .string "KIRI: We can battle if you\n"
    .string "have two BRAINROTS.$"

Route14_Text_JanIntro::
    .string "JAN: KIRI, here we go!\n"
    .string "We have to try hard!$"

Route14_Text_JanDefeat::
    .string "JAN: Eeeeh!\n"
    .string "No fair!$"

Route14_Text_JanPostBattle::
    .string "JAN: KIRI, do not worry!\n"
    .string "We try harder next time.$"

Route14_Text_JanNotEnoughMons::
    .string "JAN: Want a double battle?\n"
    .string "Bring two BRAINROTS.$"
