Route10_Text_MarkIntro::
    .string "Wow, you came all the way here?\n"
    .string "Maybe you track BRAINROTS too?\l"
    .string "Want to see my notes?$"

Route10_Text_MarkDefeat::
    .string "Humph.\n"
    .string "I am not annoyed!$"

Route10_Text_MarkPostBattle::
    .string "I have rarer BRAINROT data\n"
    .string "at home!$"

Route10_Text_ClarkIntro::
    .string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-haha!\n"
    .string "Not laughing!\l"
    .string "Just dusty tunnel air!$"

Route10_Text_ClarkPostBattle::
    .string "The echo dust makes my\n"
    .string "nose go wild.$"

Route10_Text_HermanIntro::
    .string "Hi, candidate!\n"
    .string "Want to see my BRAINROTS?$"

Route10_Text_HermanDefeat::
    .string "Oh no!\n"
    .string "My BRAINROTS!$"

Route10_Text_HermanPostBattle::
    .string "I do not like losing.\n"
    .string "I do not like anyone\l"
    .string "better than me!$"

Route10_Text_HeidiIntro::
    .string "I have tried License Halls\n"
    .string "a few times.\p"
    .string "...But I always lose.$"

Route10_Text_HeidiDefeat::
    .string "Oh!\n"
    .string "After all my training!$"

Route10_Text_HeidiPostBattle::
    .string "I noticed strange collectors\n"
    .string "near the tunnel.\p"
    .string "They kept talking about echoes.$"

Route10_Text_TrentIntro::
    .string "Ah!\n"
    .string "This mountain air is sharp!$"

Route10_Text_TrentDefeat::
    .string "That cleared my head!$"

Route10_Text_TrentPostBattle::
    .string "I feel full of mountain air!$"

Route10_Text_CarolIntro::
    .string "I feel a bit faint.\n"
    .string "I have not hiked in some time.$"

Route10_Text_CarolDefeat::
    .string "I am too tired.\n"
    .string "I was not ready.$"

Route10_Text_CarolPostBattle::
    .string "The BRAINROTS here are\n"
    .string "so chunky...\p"
    .string "I wish I could find a\n"
    .string "pink floral one.$"

Route10_Text_RockTunnelDetourToLavender::
    .string "ECHO TUNNEL\n"
    .string "Detour to MEMORY TOWN$"

Route10_Text_RockTunnel::
    .string "ECHO TUNNEL$"

Route10_Text_PowerPlant::
    .string "OLD POWER PLANT$"
