Route13_Text_SebastianIntro::
    .string "My flying BRAINROTS want\n"
    .string "to battle you!$"

Route13_Text_SebastianDefeat::
    .string "My NOOBINI combo lost?$"

Route13_Text_SebastianPostBattle::
    .string "My BRAINROTS look happy\n"
    .string "even after losing.$"

Route13_Text_SusieIntro::
    .string "People say I am good\n"
    .string "for a kid.$"

Route13_Text_SusieDefeat::
    .string "Ohh!\n"
    .string "I lost!$"

Route13_Text_SusiePostBattle::
    .string "I want to be a good\n"
    .string "candidate. I will train hard.$"

Route13_Text_ValerieIntro::
    .string "Wow!\n"
    .string "Your BADGES are too cool!$"

Route13_Text_ValerieDefeat::
    .string "Not enough!$"

Route13_Text_ValeriePostBattle::
    .string "You got those BADGES from\n"
    .string "License Examiners, right?$"

Route13_Text_GwenIntro::
    .string "My cute BRAINROTS wish\n"
    .string "to meet you.$"

Route13_Text_GwenDefeat::
    .string "Good going!\n"
    .string "You totally won!$"

Route13_Text_GwenPostBattle::
    .string "BRAINROTS grow tougher\n"
    .string "through battle.$"

Route13_Text_AlmaIntro::
    .string "I found CARBOS in a cave\n"
    .string "while exploring echoes.$"

Route13_Text_AlmaDefeat::
    .string "Oh, too bad!\n"
    .string "I messed up!$"

Route13_Text_AlmaPostBattle::
    .string "CARBOS boosted the SPEED\n"
    .string "of my BRAINROT.$"

Route13_Text_PerryIntro::
    .string "I will not lose.\n"
    .string "The wind is with me!$"

Route13_Text_PerryDefeat::
    .string "The wind turned!$"

Route13_Text_PerryPostBattle::
    .string "I am beat.\n"
    .string "I guess I will FLY home.$"

Route13_Text_LolaIntro::
    .string "Sure, I will test battle\n"
    .string "with you, sweetie.$"

Route13_Text_LolaDefeat::
    .string "Oh!\n"
    .string "You little beast!$"

Route13_Text_LolaPostBattle::
    .string "I wonder which BRAINROTS\n"
    .string "hold focus better.$"

Route13_Text_SheilaIntro::
    .string "Do you want to battle\n"
    .string "some BRAINROTS with me?$"

Route13_Text_SheilaDefeat::
    .string "It is over already?$"

Route13_Text_SheilaPostBattle::
    .string "I do not know much.\p"
    .string "I picked mine because\n"
    .string "they looked cool.$"

Route13_Text_JaredIntro::
    .string "What are you looking at?$"

Route13_Text_JaredDefeat::
    .string "Dang!\n"
    .string "Stripped gears!$"

Route13_Text_JaredPostBattle::
    .string "Move along.$"

Route13_Text_RobertIntro::
    .string "I always go with flying\n"
    .string "BRAINROTS.$"

Route13_Text_RobertDefeat::
    .string "Out of power!$"

Route13_Text_RobertPostBattle::
    .string "I wish I could fly like\n"
    .string "NOOBINI's line...$"

Route13_Text_LookToLeftOfThatPost::
    .string "TRAINER TIPS\p"
    .string "Look, look!\n"
    .string "Look left of that post!$"

Route13_Text_SelectToSwitchItems::
    .string "TRAINER TIPS\p"
    .string "Use SELECT to switch items\n"
    .string "in the ITEMS window.$"

Route13_Text_RouteSign::
    .string "SILENCE BRIDGE 13\n"
    .string "North to MEMORY TOWN$"
