Route8_Text_AidanIntro::
    .string "You look good with BRAINROTS,\n"
    .string "but how is your Cognia theory?$"

Route8_Text_AidanDefeat::
    .string "Ow!\n"
    .string "Mental meltdown!$"

Route8_Text_AidanPostBattle::
    .string "I am better at school than this!$"

Route8_Text_StanIntro::
    .string "All right!\n"
    .string "Let us play a test game!$"

Route8_Text_StanDefeat::
    .string "Drat!\n"
    .string "Came up short!$"

Route8_Text_StanPostBattle::
    .string "Things did not sync today.$"

Route8_Text_GlennIntro::
    .string "You should be informed.\n"
    .string "Strategy beats noise!$"

Route8_Text_GlennDefeat::
    .string "It is not logical!$"

Route8_Text_GlennPostBattle::
    .string "Go with a tank first... and...\n"
    .string "...then... wait, I forgot.$"

Route8_Text_PaigeIntro::
    .string "I like cute BRAINROTS,\n"
    .string "so I collect them!$"

Route8_Text_PaigeDefeat::
    .string "Why?\n"
    .string "Why??$"

Route8_Text_PaigePostBattle::
    .string "Some BRAINROTS get scarier\n"
    .string "when they evolve.\p"
    .string "Cute is safer!$"

Route8_Text_LeslieIntro::
    .string "School is fun, but so are\n"
    .string "BRAINROT battles.$"

Route8_Text_LeslieDefeat::
    .string "You made it clear that\n"
    .string "I should study more.$"

Route8_Text_LesliePostBattle::
    .string "We are stuck here because\n"
    .string "COGNIA CORE gates are locked.$"

Route8_Text_AndreaIntro::
    .string "BRRBRR is so cute, brr, brr,\n"
    .string "brr!$"

Route8_Text_AndreaDefeat::
    .string "Brrrr-yow!$"

Route8_Text_AndreaPostBattle::
    .string "I think NOOBINI and PIPIKIWI\n"
    .string "are cute too!$"

Route8_Text_MeganIntro::
    .string "We must look silly standing\n"
    .string "here like checkpoint dolls.$"

Route8_Text_MeganDefeat::
    .string "Look what you did to my\n"
    .string "cute BRAINROT!$"

Route8_Text_MeganPostBattle::
    .string "COGNIA CORE's gatekeeper\n"
    .string "will not let us through.\p"
    .string "I know it is his job,\n"
    .string "but it feels mean.$"

Route8_Text_RichIntro::
    .string "I am a rambling, gaming dude!$"

Route8_Text_RichDefeat::
    .string "Missed the big chance!$"

Route8_Text_RichPostBattle::
    .string "Games and BRAINROTS are\n"
    .string "too easy to get hooked on!$"

Route8_Text_JuliaIntro::
    .string "What is cute, round,\n"
    .string "and a little noisy?$"

Route8_Text_JuliaDefeat::
    .string "Stop!\p"
    .string "Do not be mean to my cutie!$"

Route8_Text_JuliaPostBattle::
    .string "I read some BRAINROTS react\n"
    .string "to MOON STONE echoes.\p"
    .string "I wonder if it is true?$"

Route8_Text_UndergroundPathSign::
    .string "UNDERGROUND SAFE PATH\n"
    .string "SKIBIDY CITY - MEMORY TOWN$"

Route8_Text_EliIntro::
    .string "ELI: Twin focus is fantastic.\n"
    .string "Did you know?$"

Route8_Text_EliDefeat::
    .string "ELI: But...\n"
    .string "We used twin focus...$"

Route8_Text_EliPostBattle::
    .string "ELI: I caught my BRAINROT\n"
    .string "with ANNE!$"

Route8_Text_EliNotEnoughMons::
    .string "ELI: We cannot battle if you\n"
    .string "do not have two BRAINROTS.$"

Route8_Text_AnneIntro::
    .string "ANNE: We will shock you\n"
    .string "with twin focus!$"

Route8_Text_AnneDefeat::
    .string "ANNE: Our twin focus...$"

Route8_Text_AnnePostBattle::
    .string "ANNE: I am raising BRAINROTS\n"
    .string "with ELI.$"

Route8_Text_AnneNotEnoughMons::
    .string "ANNE: Hi, hi! Let us battle!\n"
    .string "But bring two BRAINROTS.$"

Route8_Text_RicardoIntro::
    .string "My bike is acting up, man.$"

Route8_Text_RicardoDefeat::
    .string "Aww, man.\n"
    .string "I am not into this.$"

Route8_Text_RicardoPostBattle::
    .string "I got route grass caught\n"
    .string "in my spokes, man.$"

Route8_Text_JarenIntro::
    .string "Clear the way, or I will\n"
    .string "rush past you!$"

Route8_Text_JarenDefeat::
    .string "You for real, candidate?$"

Route8_Text_JarenPostBattle::
    .string "Do not think you are special\n"
    .string "just because of this.$"
